# Copyright (c) 2017-2020 Michael C. Heiber
# This source file is part of the KMC_Lattice project, which is subject to the MIT License.
# For more information, see the LICENSE file that accompanies this software.
# The KMC_Lattice project can be found on Github at https://github.com/MikeHeiber/KMC_Lattice
# Travis CI continuous integration build script

language: cpp
sudo: required

jobs:
    include:
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=5 && MPI=openmpi && TARGET=test_coverage"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=5 && MPI=mpich2 && TARGET=test"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=5 && MPI=openmpi && TARGET=test"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=6 && MPI=mpich2 && TARGET=test"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=6 && MPI=openmpi && TARGET=test"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=7 && MPI=mpich2 && TARGET=test"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=7 && MPI=openmpi && TARGET=test"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=8 && MPI=mpich2 && TARGET=test"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=8 && MPI=openmpi && TARGET=test"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=9 && MPI=mpich2 && TARGET=test"
        - os: linux
          dist: xenial
          compiler: gcc
          env:
            - OPTIONS="GCC_VERSION=9 && MPI=openmpi && TARGET=test"
                - os: linux
          dist: xenial
          compiler: clang
          env:
           - OPTIONS="MPI=mpich2 && TARGET=test"
        - os: linux
          dist: xenial
          compiler: clang
          env:
            - OPTIONS="MPI=openmpi && TARGET=test"

before_install:
    - eval "${OPTIONS}"
    - if [[ "$TRAVIS_COMPILER" = gcc ]]; then
    -   sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    -   sudo apt-get update -qq
    -   sudo apt-get install -qq gcc-$GCC_VERSION g++-$GCC_VERSION -y
    -   sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-$GCC_VERSION 60 --slave /usr/bin/g++ g++ /usr/bin/g++-$GCC_VERSION
    -   sudo update-alternatives --config gcc
    -   gcc --version
    - fi
    - if [[ "$TRAVIS_COMPILER" = clang ]]; then
    -   sudo apt install clang -y
    -   export OMPI_CXX=clang++
    -   export CXX=clang++
    - fi
    - if [[ "$MPI" = mpich2 ]]; then sudo apt-get -y install -qq mpich2 libmpich2-dev; fi
    - if [[ "$MPI" = openmpi ]]; then sudo apt-get -y install -qq openmpi-bin libopenmpi-dev; fi
    - if [[ "$TARGET" = test_coverage ]]; then pip install --user cpp-coveralls; fi
    
script:
    - make -j10 $TARGET && travis_wait ./test/KMC_Lattice_tests.exe && travis_wait mpiexec -n 4 ./test/KMC_Lattice_MPI_tests.exe
    - if [[ "$TARGET" = test_coverage ]]; then coveralls --include src --exclude "googletest/*" --gcov-options '\-lp'; fi
